users:
  admins:
    - username: admin
      password: admin
      roles: ADMIN
    - username: admin1
      password: admin1
      roles: ADMIN
  whs:
    - username: wh
      password: wh
      roles: USER_WH
    - username: wh1
      password: wh1
      roles: USER_WH  
  pdcs:
    - username: pdc
      password: pdc
      roles: USER_PDC
    - username: pdc1
      password: pdc1
      roles: USER_PDC   